export type VariableEvidence = {
  field: string
  category: string
  sourceDefinition: string
  websiteMapping: string
  status: 'Direct' | 'Converted' | 'Project-derived' | 'Formal result'
  limitation: string
}

export const variableEvidence: VariableEvidence[] = [
  { field: 'Age', category: 'Demographics', sourceDefinition: 'Age in years, 60-90.', websiteMapping: 'User enters age in years.', status: 'Direct', limitation: 'The deployed model does not support ages outside the source range.' },
  { field: 'Gender', category: 'Demographics', sourceDefinition: '0=male, 1=female.', websiteMapping: 'The same binary coding is used.', status: 'Direct', limitation: 'The source dataset contains no additional gender categories.' },
  { field: 'Ethnicity', category: 'Demographics', sourceDefinition: '0=Caucasian, 1=African American, 2=Asian, 3=Other.', websiteMapping: 'User selects the corresponding source category.', status: 'Direct', limitation: 'Broad categories may conceal within-group differences.' },
  { field: 'EducationLevel', category: 'Demographics', sourceDefinition: "0=None, 1=High School, 2=Bachelor's, 3=Higher.", websiteMapping: 'User selects the corresponding source category.', status: 'Direct', limitation: 'The categories do not capture years or quality of education.' },
  { field: 'BMI', category: 'Lifestyle', sourceDefinition: 'Body mass index, 15-40.', websiteMapping: 'Calculated from height in centimetres and weight in kilograms.', status: 'Converted', limitation: 'Self-reported height and weight may contain error.' },
  { field: 'Smoking', category: 'Lifestyle', sourceDefinition: '0=no, 1=yes.', websiteMapping: 'User reports current smoking status.', status: 'Direct', limitation: 'Duration and previous smoking are not represented.' },
  { field: 'AlcoholConsumption', category: 'Lifestyle', sourceDefinition: 'Weekly alcohol consumption in units, 0-20.', websiteMapping: 'Beer, wine and spirits are converted to UK units and capped at 20 for the model.', status: 'Converted', limitation: 'The source data card does not establish that its unit definition is identical to UK units.' },
  { field: 'PhysicalActivity', category: 'Lifestyle', sourceDefinition: 'Weekly physical activity in hours, 0-10.', websiteMapping: 'Moderate minutes plus twice vigorous minutes are converted to equivalent hours per week.', status: 'Converted', limitation: 'Intensity weighting is a BrainEcho operational rule, not a validated source-dataset instrument.' },
  { field: 'DietQuality', category: 'Lifestyle', sourceDefinition: 'Diet quality score, 0-10.', websiteMapping: 'Six food-frequency answers are converted to a BrainEcho score. Fish or seafood intake is reported as approximate weekly portions of 100 g.', status: 'Project-derived', limitation: 'The original scoring instrument is not supplied, so measurement equivalence is not established. Portion estimates are self-reported and are not a formal dietary assessment.' },
  { field: 'SleepQuality', category: 'Lifestyle', sourceDefinition: 'Sleep quality score, 4-10.', websiteMapping: 'Sleep duration, waking and daytime sleepiness form a BrainEcho score.', status: 'Project-derived', limitation: 'The formula is not the original source-dataset measurement instrument.' },
  { field: 'FamilyHistoryAlzheimers', category: 'Medical history', sourceDefinition: '0=no, 1=yes.', websiteMapping: 'User reports an Alzheimer diagnosis in a close relative.', status: 'Direct', limitation: 'Family relationship and diagnostic certainty are not captured.' },
  { field: 'CardiovascularDisease', category: 'Medical history', sourceDefinition: '0=no, 1=yes.', websiteMapping: 'User reports a previous diagnosis.', status: 'Direct', limitation: 'Disease subtype and severity are not recorded.' },
  { field: 'Diabetes', category: 'Medical history', sourceDefinition: '0=no, 1=yes.', websiteMapping: 'User reports a previous diagnosis.', status: 'Direct', limitation: 'Type, duration and control are not recorded.' },
  { field: 'Depression', category: 'Medical history', sourceDefinition: '0=no, 1=yes.', websiteMapping: 'User reports a previous diagnosis.', status: 'Direct', limitation: 'Current symptoms and treatment are not recorded.' },
  { field: 'HeadInjury', category: 'Medical history', sourceDefinition: '0=no, 1=yes.', websiteMapping: 'User reports serious head injury history.', status: 'Direct', limitation: 'Timing, number and severity are not modelled.' },
  { field: 'Hypertension', category: 'Medical history', sourceDefinition: '0=no, 1=yes.', websiteMapping: 'User reports a previous diagnosis.', status: 'Direct', limitation: 'Treatment and duration are not represented.' },
  { field: 'SystolicBP', category: 'Clinical measurements', sourceDefinition: 'Systolic blood pressure, 90-180 mmHg.', websiteMapping: 'User enters a recent measurement in mmHg.', status: 'Direct', limitation: 'A single self-reported reading may not represent usual blood pressure.' },
  { field: 'DiastolicBP', category: 'Clinical measurements', sourceDefinition: 'Diastolic blood pressure, 60-120 mmHg.', websiteMapping: 'User enters a recent measurement in mmHg.', status: 'Direct', limitation: 'A single self-reported reading may not represent usual blood pressure.' },
  { field: 'CholesterolTotal', category: 'Clinical measurements', sourceDefinition: 'Total cholesterol, 150-300 mg/dL.', websiteMapping: 'mg/dL is used directly; mmol/L is converted.', status: 'Converted', limitation: 'The date and fasting status of the test may differ.' },
  { field: 'CholesterolLDL', category: 'Clinical measurements', sourceDefinition: 'LDL cholesterol, 50-200 mg/dL.', websiteMapping: 'mg/dL is used directly; mmol/L is converted.', status: 'Converted', limitation: 'Laboratory methods are not captured.' },
  { field: 'CholesterolHDL', category: 'Clinical measurements', sourceDefinition: 'HDL cholesterol, 20-100 mg/dL.', websiteMapping: 'mg/dL is used directly; mmol/L is converted.', status: 'Converted', limitation: 'Laboratory methods are not captured.' },
  { field: 'CholesterolTriglycerides', category: 'Clinical measurements', sourceDefinition: 'Triglycerides, 50-400 mg/dL.', websiteMapping: 'mg/dL is used directly; mmol/L uses a triglyceride-specific conversion.', status: 'Converted', limitation: 'Fasting status can affect the reported value.' },
  { field: 'MMSE', category: 'Cognition and function', sourceDefinition: 'Formal MMSE score, 0-30; lower values indicate impairment.', websiteMapping: 'Only an existing formal result enters the field; the website self-check is excluded.', status: 'Formal result', limitation: 'Interpretation depends on language, education, conditions and clinical context.' },
  { field: 'FunctionalAssessment', category: 'Cognition and function', sourceDefinition: 'Functional assessment score, 0-10; lower values indicate greater impairment.', websiteMapping: 'Eight independent activities form a BrainEcho checklist score.', status: 'Project-derived', limitation: 'The source instrument and scoring rules are not supplied.' },
  { field: 'MemoryComplaints', category: 'Cognition and function', sourceDefinition: '0=no, 1=yes.', websiteMapping: 'User reports repeated memory concerns.', status: 'Direct', limitation: 'Self-report can differ from informant or clinical assessment.' },
  { field: 'BehavioralProblems', category: 'Cognition and function', sourceDefinition: '0=no, 1=yes.', websiteMapping: 'User reports repeated emotional or behavioural change.', status: 'Direct', limitation: 'The source variable does not provide a validated symptom scale.' },
  { field: 'ADL', category: 'Cognition and function', sourceDefinition: 'Activities of daily living score, 0-10; lower values indicate greater impairment.', websiteMapping: 'Six basic activities form a BrainEcho checklist score.', status: 'Project-derived', limitation: 'This is not presented as a licensed Katz ADL score.' },
  { field: 'Confusion', category: 'Symptoms', sourceDefinition: '0=no, 1=yes.', websiteMapping: 'User reports confusion.', status: 'Direct', limitation: 'Sudden confusion may have causes requiring urgent assessment and is not specific to Alzheimer disease.' },
  { field: 'Disorientation', category: 'Symptoms', sourceDefinition: '0=no, 1=yes.', websiteMapping: 'User reports difficulty identifying time or place.', status: 'Direct', limitation: 'Frequency, onset and context are not represented.' },
  { field: 'PersonalityChanges', category: 'Symptoms', sourceDefinition: '0=no, 1=yes.', websiteMapping: 'User reports noticeable personality change.', status: 'Direct', limitation: 'The question is subjective and not disorder-specific.' },
  { field: 'DifficultyCompletingTasks', category: 'Symptoms', sourceDefinition: '0=no, 1=yes.', websiteMapping: 'User reports increasing difficulty with familiar tasks.', status: 'Direct', limitation: 'Physical, sensory and environmental explanations are not separated.' },
  { field: 'Forgetfulness', category: 'Symptoms', sourceDefinition: '0=no, 1=yes.', websiteMapping: 'User reports frequent recent forgetfulness.', status: 'Direct', limitation: 'Duration, severity and alternative causes are not captured.' },
]
